package pt.ipp.isep.dei.controller.terminalOperator;

import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import pt.ipp.isep.dei.domain.Log;
import pt.ipp.isep.dei.domain.RoleType;
import pt.ipp.isep.dei.data.repository.LogRepository;
import pt.ipp.isep.dei.data.repository.Repositories;

import java.util.HashSet;
import java.util.Set;

/**
 * Controller responsible for managing the Warehouse Management System (WMS)
 * logs accessible to the Terminal Operator.
 * <p>
 * Provides filtering capabilities by role type, allowing the Terminal Operator
 * to view system logs generated by specific user roles.
 */
public class TerminalOperatorWmsController {

    private final LogRepository logRepository;

    private boolean globalSelected;
    private boolean pickerSelected;
    private boolean plannerSelected;
    private boolean qualityOperatorSelected;
    private boolean terminalOperatorSelected;
    private boolean trafficDispatcherSelected;
    private boolean warehousePlannerSelected;

    /**
     * Initializes the controller and retrieves the LogRepository instance.
     */
    public TerminalOperatorWmsController() {
        this.logRepository = Repositories.getInstance().getLogRepository();
    }

    /** @param globalSelected sets the global role filter state. */
    public void setGlobalSelected(boolean globalSelected) { this.globalSelected = globalSelected; }

    /** @param pickerSelected sets the picker role filter state. */
    public void setPickerSelected(boolean pickerSelected) { this.pickerSelected = pickerSelected; }

    /** @param plannerSelected sets the planner role filter state. */
    public void setPlannerSelected(boolean plannerSelected) { this.plannerSelected = plannerSelected; }

    /** @param qualityOperatorSelected sets the quality operator role filter state. */
    public void setQualityOperatorSelected(boolean qualityOperatorSelected) { this.qualityOperatorSelected = qualityOperatorSelected; }

    /** @param terminalOperatorSelected sets the terminal operator role filter state. */
    public void setTerminalOperatorSelected(boolean terminalOperatorSelected) { this.terminalOperatorSelected = terminalOperatorSelected; }

    /** @param trafficDispatcherSelected sets the traffic dispatcher role filter state. */
    public void setTrafficDispatcherSelected(boolean trafficDispatcherSelected) { this.trafficDispatcherSelected = trafficDispatcherSelected; }

    /** @param warehousePlannerSelected sets the warehouse planner role filter state. */
    public void setWarehousePlannerSelected(boolean warehousePlannerSelected) { this.warehousePlannerSelected = warehousePlannerSelected; }

    /**
     * Enables all role filters simultaneously, displaying logs from all roles.
     */
    public void selectAllRoles() {
        globalSelected = true;
        pickerSelected = true;
        plannerSelected = true;
        qualityOperatorSelected = true;
        terminalOperatorSelected = true;
        trafficDispatcherSelected = true;
        warehousePlannerSelected = true;
    }

    /**
     * Disables all role filters, effectively hiding all role-based logs.
     */
    public void clearAllRoles() {
        globalSelected = false;
        pickerSelected = false;
        plannerSelected = false;
        qualityOperatorSelected = false;
        terminalOperatorSelected = false;
        trafficDispatcherSelected = false;
        warehousePlannerSelected = false;
    }

    /**
     * Retrieves a filtered list of logs based on the currently selected roles.
     *
     * @return an observable list containing the string representation of logs
     *         matching the selected roles.
     */
    public ObservableList<String> getFilteredLogs() {
        ObservableList<String> filteredLogs = FXCollections.observableArrayList();
        Set<RoleType> selectedRoles = new HashSet<>();
        if (globalSelected) selectedRoles.add(RoleType.GLOBAL);
        if (pickerSelected) selectedRoles.add(RoleType.PICKER);
        if (plannerSelected) selectedRoles.add(RoleType.PLANNER1);
        if (qualityOperatorSelected) selectedRoles.add(RoleType.QUALITY_OPERATOR);
        if (terminalOperatorSelected) selectedRoles.add(RoleType.TERMINAL_OPERATOR);
        if (trafficDispatcherSelected) selectedRoles.add(RoleType.TRAFFIC_DISPATCHER);
        if (warehousePlannerSelected) selectedRoles.add(RoleType.WAREHOUSE_PLANNER);

        for (Log log : logRepository.findAll()) {
            if (selectedRoles.contains(log.getRoleType())) {
                filteredLogs.add(log.toString());
            }
        }
        return filteredLogs;
    }

    /**
     * Finds the role type associated with a specific log entry string.
     *
     * @param logString the string representation of a log.
     * @return the corresponding {@link RoleType}, or null if not found.
     */
    public RoleType getRoleTypeForLog(String logString) {
        for (Log log : logRepository.findAll()) {
            if (log.toString().equals(logString)) {
                return log.getRoleType();
            }
        }
        return null;
    }
}
