package pt.ipp.isep.dei.controller.routePlanner;

import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import pt.ipp.isep.dei.data.repository.LogRepository;
import pt.ipp.isep.dei.data.repository.Repositories;
import pt.ipp.isep.dei.domain.Log;
import pt.ipp.isep.dei.domain.RoleType;

import java.util.HashSet;
import java.util.Set;

/**
 * Controller responsible for managing the Warehouse Management System (WMS)
 * logs accessible to the Terminal Operator.
 * <p>
 * Provides filtering capabilities by role type, allowing the Terminal Operator
 * to view system logs generated by specific user roles.
 */
public class RoutePlannerNOSController {

    private final LogRepository logRepository;

    private boolean globalSelected;
    private boolean freightManagerSelected;
    private boolean infrastructurePlannerSelected;
    private boolean maintenancePlannerSelected;
    private boolean operationsAnalystSelected;
    private boolean routePlannerSelected;
    private boolean trafficManagerSelected;
    /**
     * Initializes the controller and retrieves the LogRepository instance.
     */
    public RoutePlannerNOSController() {
        this.logRepository = Repositories.getInstance().getLogRepository();
    }

    /** @param globalSelected sets the global role filter state. */
    public void setGlobalSelected(boolean globalSelected) { this.globalSelected = globalSelected; }

    public void setFreightManagerSelected(boolean freightManagerSelected) {
        this.freightManagerSelected = freightManagerSelected;
    }

    public void setInfrastructurePlannerSelected(boolean infrastructurePlannerSelected) {
        this.infrastructurePlannerSelected = infrastructurePlannerSelected;
    }

    public void setMaintenancePlannerSelected(boolean maintenancePlannerSelected) {
        this.maintenancePlannerSelected = maintenancePlannerSelected;
    }

    public void setOperationsAnalystSelected(boolean operationsAnalystSelected) {
        this.operationsAnalystSelected = operationsAnalystSelected;
    }

    public void setRoutePlannerSelected(boolean routePlannerSelected) {
        this.routePlannerSelected = routePlannerSelected;
    }

    public void setTrafficManagerSelected(boolean trafficManagerSelected) {
        this.trafficManagerSelected = trafficManagerSelected;
    }

    /**
     * Enables all role filters simultaneously, displaying logs from all roles.
     */
    public void selectAllRoles() {
        globalSelected = true;
        freightManagerSelected = true;
        infrastructurePlannerSelected = true;
        maintenancePlannerSelected = true;
        operationsAnalystSelected = true;
        routePlannerSelected = true;
        trafficManagerSelected = true;
    }

    /**
     * Disables all role filters, effectively hiding all role-based logs.
     */
    public void clearAllRoles() {
        globalSelected = false;
        freightManagerSelected = false;
        infrastructurePlannerSelected = false;
        maintenancePlannerSelected = false;
        operationsAnalystSelected = false;
        routePlannerSelected = false;
        trafficManagerSelected = false;
    }

    /**
     * Retrieves a filtered list of logs based on the currently selected roles.
     *
     * @return an observable list containing the string representation of logs
     *         matching the selected roles.
     */
    public ObservableList<String> getFilteredLogs() {
        ObservableList<String> filteredLogs = FXCollections.observableArrayList();
        Set<RoleType> selectedRoles = new HashSet<>();
        if (globalSelected) selectedRoles.add(RoleType.GLOBAL);
        if (freightManagerSelected) selectedRoles.add(RoleType.FREIGHT_MANAGER3);
        if (infrastructurePlannerSelected) selectedRoles.add(RoleType.INFRASTRUCTURE_PLANNER);
        if (maintenancePlannerSelected) selectedRoles.add(RoleType.MAINTENANCE_PLANNER);
        if (operationsAnalystSelected) selectedRoles.add(RoleType.OPERATIONS_ANALYST);
        if (routePlannerSelected) selectedRoles.add(RoleType.ROUTE_PLANNER);
        if (trafficManagerSelected) selectedRoles.add(RoleType.TRAFFIC_MANAGER);

        for (Log log : logRepository.findAll()) {
            if (selectedRoles.contains(log.getRoleType())) {
                filteredLogs.add(log.toString());
            }
        }
        return filteredLogs;
    }

    /**
     * Finds the role type associated with a specific log entry string.
     *
     * @param logString the string representation of a log.
     * @return the corresponding {@link RoleType}, or null if not found.
     */
    public RoleType getRoleTypeForLog(String logString) {
        for (Log log : logRepository.findAll()) {
            if (log.toString().equals(logString)) {
                return log.getRoleType();
            }
        }
        return null;
    }
}
