module project.template {
    requires javafx.fxml;
    requires jdk.jshell;
    requires java.sql;
    requires jdk.compiler;
    requires java.naming;
    requires javafx.controls;
    requires java.desktop;
    requires com.oracle.database.jdbc;
    requires javafx.graphics;
    requires javafx.base;
    requires guru.nidi.graphviz;
    requires gs.core;
    requires gs.ui.javafx;
    requires javafx.web;

    opens pt.ipp.isep.dei to javafx.fxml;
    opens pt.ipp.isep.dei.ui.gui to javafx.fxml;
    opens pt.ipp.isep.dei.ui.gui.visitorMenu to javafx.fxml;
    opens pt.ipp.isep.dei.ui.gui.admin to javafx.fxml;
    opens pt.ipp.isep.dei.ui.gui.login to javafx.fxml;
    opens pt.ipp.isep.dei.ui.gui.wareHousePlanner to javafx.fxml;
    opens pt.ipp.isep.dei.ui.gui.terminalOperator to javafx.fxml;
    opens pt.ipp.isep.dei.ui.gui.picker to javafx.fxml;
    opens pt.ipp.isep.dei.ui.gui.planner to javafx.fxml;
    opens pt.ipp.isep.dei.ui.gui.qualityOperator to javafx.fxml;
    opens pt.ipp.isep.dei.ui.gui.trafficDispatcher to javafx.fxml;
    opens pt.ipp.isep.dei.ui.gui.dataEngineer to javafx.fxml;
    opens pt.ipp.isep.dei.ui.gui.analyst to javafx.fxml;
    opens pt.ipp.isep.dei.ui.gui.operationsPlanner to javafx.fxml;
    opens pt.ipp.isep.dei.ui.gui.freightManager to javafx.fxml;
    opens pt.ipp.isep.dei.ui.gui.operationsAnalyst to javafx.fxml;
    opens pt.ipp.isep.dei.ui.gui.freightManager.routeRelated to javafx.fxml;
    opens pt.ipp.isep.dei.ui.gui.routePlanner to javafx.fxml;
    opens pt.ipp.isep.dei.ui.gui.trafficManager to javafx.fxml;
    opens pt.ipp.isep.dei.ui.gui.trafficManager.pathRelated to javafx.fxml;
    opens pt.ipp.isep.dei.ui.gui.infrastructurePlanner to javafx.fxml;
    opens pt.ipp.isep.dei.ui.gui.maintenancePlanner to javafx.fxml;

    exports pt.ipp.isep.dei;
    exports pt.ipp.isep.dei.domain;
    exports pt.ipp.isep.dei.domain.BoxRelated;
    exports pt.ipp.isep.dei.domain.OrderRelated;
    exports pt.ipp.isep.dei.domain.trolleyRelated;
    exports pt.ipp.isep.dei.data.repository;
    exports pt.ipp.isep.dei.utils;
    exports pt.ipp.isep.dei.ui.console;

    exports pt.ipp.isep.dei.ui.gui;
    exports pt.ipp.isep.dei.ui.gui.visitorMenu;
    exports pt.ipp.isep.dei.ui.gui.admin;
    exports pt.ipp.isep.dei.ui.gui.login;
    exports pt.ipp.isep.dei.ui.gui.terminalOperator;
    exports pt.ipp.isep.dei.ui.gui.picker to javafx.fxml;
    exports pt.ipp.isep.dei.ui.gui.planner;
    exports pt.ipp.isep.dei.ui.gui.wareHousePlanner;
    exports pt.ipp.isep.dei.ui.gui.qualityOperator;
    exports pt.ipp.isep.dei.ui.gui.trafficDispatcher;
    exports pt.ipp.isep.dei.ui.gui.dataEngineer;
    exports pt.ipp.isep.dei.ui.gui.analyst;
    exports pt.ipp.isep.dei.ui.gui.operationsPlanner;
    exports pt.ipp.isep.dei.domain.wagonRelated;
    exports pt.ipp.isep.dei.domain.transportationRelated;
    exports pt.ipp.isep.dei.ui.gui.freightManager;
    exports pt.ipp.isep.dei.domain.ESINF;
    exports pt.ipp.isep.dei.data.repository.sprint1;
    exports pt.ipp.isep.dei.data.repository.sprint2;
    exports pt.ipp.isep.dei.data.repository.sprint3;
    exports pt.ipp.isep.dei.ui.gui.routePlanner;
    exports pt.ipp.isep.dei.domain.trackRelated;
    exports pt.ipp.isep.dei.ui.gui.trafficManager;
    exports pt.ipp.isep.dei.ui.gui.trafficManager.pathRelated;
    exports pt.ipp.isep.dei.ui.gui.infrastructurePlanner;
    exports pt.ipp.isep.dei.ui.gui.maintenancePlanner;
    exports pt.ipp.isep.dei.ui.gui.freightManager.trainRelated;
    opens pt.ipp.isep.dei.ui.gui.freightManager.trainRelated to javafx.fxml;
}
