package pt.ipp.isep.dei.controller.picker;

import pt.ipp.isep.dei.domain.BoxRelated.Box;
import pt.ipp.isep.dei.domain.pickingPath.PickingPathReport;
import pt.ipp.isep.dei.data.repository.sprint1.AisleRepository;
import pt.ipp.isep.dei.data.repository.sprint1.BayRepository;
import pt.ipp.isep.dei.data.repository.Repositories;

/**
 * Controller that manages and compares results from different picking strategies.
 * <p>
 * Provides access to picking path reports and utility methods for retrieving
 * aisle and bay numbers and calculating total distances.
 */
public class StrategiesController {

    private PickingPathReport pickingPathReportA;
    private PickingPathReport pickingPathReportB;
    private AisleRepository aisleRepository;
    private BayRepository bayRepository;

    /**
     * Default constructor that initializes the repositories.
     */
    public StrategiesController() {
        initRepos();
    }

    /**
     * Initializes the repository instances from {@link Repositories}.
     */
    private void initRepos() {
        aisleRepository = Repositories.getInstance().getAisleRepository();
        bayRepository = Repositories.getInstance().getBayRepository();
    }

    /**
     * Sets the picking path reports for both strategies.
     *
     * @param pickingPathReportA the report generated by Strategy A
     * @param pickingPathReportB the report generated by Strategy B
     */
    public void setData(PickingPathReport pickingPathReportA, PickingPathReport pickingPathReportB) {
        this.pickingPathReportA = pickingPathReportA;
        this.pickingPathReportB = pickingPathReportB;
    }

    /**
     * Gets the picking path report generated by Strategy A.
     *
     * @return the {@link PickingPathReport} for Strategy A
     */
    public PickingPathReport getPickingPathReportA() {
        return pickingPathReportA;
    }

    /**
     * Sets the picking path report for Strategy A.
     *
     * @param pickingPathReportA the report to assign
     */
    public void setPickingPathReportA(PickingPathReport pickingPathReportA) {
        this.pickingPathReportA = pickingPathReportA;
    }

    /**
     * Gets the picking path report generated by Strategy B.
     *
     * @return the {@link PickingPathReport} for Strategy B
     */
    public PickingPathReport getPickingPathReportB() {
        return pickingPathReportB;
    }

    /**
     * Sets the picking path report for Strategy B.
     *
     * @param pickingPathReportB the report to assign
     */
    public void setPickingPathReportB(PickingPathReport pickingPathReportB) {
        this.pickingPathReportB = pickingPathReportB;
    }

    /**
     * Retrieves the aisle number of a given box.
     *
     * @param box the box whose aisle number is to be retrieved
     * @return a string representing the aisle number
     */
    public String getAisleNumber(Box box) {
        return String.valueOf(
                aisleRepository.findByKey(
                        bayRepository.findByKey(box.getBayId()).getAisleId()
                ).getNumber()
        );
    }

    /**
     * Retrieves the bay number of a given box.
     *
     * @param box the box whose bay number is to be retrieved
     * @return a string representing the bay number
     */
    public String getBayNumber(Box box) {
        return String.valueOf(
                bayRepository.findByKey(box.getBayId()).getBay()
        );
    }

    /**
     * Calculates the total distance covered in a given picking path report.
     *
     * @param pickingPathReport the report to analyze
     * @return the total distance value
     */
    public double getTotalDistance(PickingPathReport pickingPathReport) {
        return pickingPathReport.getTotalDistance();
    }
}
